postgres:
  host: postgres-postgresql-primary
  port: 5432
  user: kisiel
  password: EogqJDdd#2^S6LJ!zqXUw!&rU@G45cPU

retention:
  # retention time (in seconds)
  time: 7776000
  # frequency of retention execution (in seconds)
  frequency: 60
  # database and table names
  # eg.
  # database_name: table1, table2
  # wildcard "*" means all the tables will be affected
  # database_name: *
  targets: |
    bb_icmarkets: *
    other_db: balance1, balance2