image: wiktorkisielewski/postgres-retention-sidecar
imageTag: 0.1.1

imagePullPolicy: IfNotPresent

resources:
  requests:
    memory: "32Mi"
    cpu: "0.1"
  limits:
    memory: "64Mi"
    cpu: "0.1"
