apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-retention-sidecar
  labels:
    app: psql-retention-sidecar
spec:
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: psql-retention-sidecar
  template:
    metadata:
      labels:
        app: psql-retention-sidecar
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: psql-retention-sidecar
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: psql-retention-settings
          mountPath: /targets.yml
          subPath: targets.yml
          readOnly: true
      volumes:
      - configMap:
          name: psql-retention-settings
        name: psql-retention-settings
        # emptyDir: {}
